// export const DOMAIN = 'http://localhost:3000';
export const DOMAIN = 'https://www.readmyheroacademia.online';

export const DOMAIN_NAME = 'readmyheroacademia.online';

export const IMAGES_SUBDOMAIN = 'https://images.mangachimp.com/my-hero-academia';
export const IMAGES_SUBDOMAIN_LOGO = 'https://images.mangachimp.com';

// export const MANGA_DESCRIPTION0 = `<a href="${DOMAIN}"><u>Vinland Saga</u></a>`;

export const MANGA_DESCRIPTION = `<a href="${DOMAIN}"><u><b>My Hero Academia</b></u></a> is a popular Japanese anime and manga series set in a world where nearly everyone has superpowers, called "Quirks." The story follows Izuku Midoriya, a boy born without a Quirk, who dreams of becoming a hero. He inherits the powerful Quirk "One For All" from the world’s greatest hero, All Might. Izuku then enrolls in U.A. High School, where he trains alongside other young heroes-in-training. The series explores themes of heroism, friendship, and the struggle between good and evil, while showcasing intense battles and character development.`;



export const MANGA_NAME = 'My Hero Academia';
export const MANGA_AUTHOR = 'KōHei Horikoshi';
export const MANGA_RELEASE = '2014';
export const MANGA_STATUS = 'Ongoing';
export const MANGA_ARTIST = 'Fujino Ōmori';
export const MANGA_STUDIO = 'None';
export const MANGA_GENRE = 'Action, Adventure, Drama, Shonen, Fantasy, School';
export const MANGA_TYPE = 'Manhwa';
export const HEADER_MANGA_DESC = "The story follows Izuku Midoriya, a boy born without a Quirk, who dreams of becoming a hero. He inherits the powerful Quirk One For All from the world’s greatest hero, All Might. Izuku then enrolls in U.A. High School, where he trains alongside other young heroes-in-training. The series explores themes of heroism, friendship, and the struggle between good and evil, while showcasing intense battles and character development."

export const CHAPTER_PREFIX = 'chapter';
export const IMAGE_PREFIX = 'images/vinland-saga';
export const NEXT_PREVIOUS_PREFIX = 'chapter';
export const URL_PREFIX = 'chapter';

export const AUTHOR_PAGE = `${DOMAIN}/mha-team`;
export const LOGO_URL = `${DOMAIN}/logo.webp`;
export const COVER_IMG = `${DOMAIN}/cover1.webp`;
export const BEHIND_COVER_IMG = "";


// Navbar
export const logo = <img src={`${LOGO_URL}`} alt="Logo" className="h-[75px] w-[75px] rounded-[75%] mr-5 md:ml-0 ml-4 md:pb-2 md:my-0 my-1" />

export const APP_NAME = 'My Hero Academia';
export const NavbarName = "My Hero Academia";

export const APP_DESCRIPTION = `Read ${MANGA_NAME} manga online at ${DOMAIN_NAME}. ${HEADER_MANGA_DESC}`;

export const DISQUS_SHORTNAME = "my-cms-7";


export const MANGA_SUMMARY = [
    {
        id: 1,
        content: "My Hero Academia is a Japanese anime and manga series created by Kohei Horikoshi. The story is set in a world where almost 80% of the population possesses unique superpowers, known as Quirks. These powers range from simple abilities like changing hair color to extraordinary ones like manipulating fire or controlling gravity. In this super-powered society, being a superhero is a recognized profession, and heroes serve to protect citizens from villains who misuse their Quirks."
    },
    {
        id: 2,
        content: "The protagonist, Izuku Midoriya, is one of the rare individuals born without a Quirk, but he idolizes the world’s greatest hero, All Might. Despite lacking powers, Izuku dreams of becoming a hero himself. His life changes when he meets All Might, who sees potential in him. All Might is the holder of a powerful Quirk known as One For All,  which can be passed down from person to person, enhancing its strength with each successor. Seeing Izuku’s courage and determination, All Might decides to transfer his Quirk to him, making Izuku his successor."
    },
    {
        id: 3,
        content: "After receiving this incredible power, Izuku enrolls in U.A. High School, an elite academy for aspiring heroes. There, he meets other students with extraordinary abilities, including Katsuki Bakugo, his childhood rival, and Ochaco Uraraka, who becomes one of his closest friends. The students undergo rigorous training, learn about heroism, and face various challenges designed to test their abilities. Throughout the series, Izuku must learn to control his new Quirk, while also confronting his insecurities and the responsibility of carrying All Might’s legacy."
    },
    {
        id: 4,
        content: "In addition to hero training, the students encounter dangerous villains, most notably the League of Villains, led by Tomura Shigaraki. Shigaraki aims to overthrow the hero society and is connected to a far more sinister force, All For One, the arch-nemesis of All Might and the previous wielder of the Quirk One For All. The conflict between the heroes and villains escalates as the story progresses, with increasingly intense battles and emotional stakes."
    },
    {
        id: 5,
        content: "My Hero Academia explores themes of heroism, justice, and sacrifice, as well as the societal expectations placed on heroes. Izuku’s journey is one of self-discovery, as he learns what it truly means to be a hero, not just in terms of power but also in moral character. The series also focuses on the relationships between the students, their growth as individuals, and the weight of their ambitions."
    },
    {
        id: 6,
        content: "As the story continues, Izuku and his classmates face greater challenges, both from within U.A. and from the growing threat of the villains. The narrative balances moments of lighthearted school life with intense, dramatic confrontations, making My Hero Academia a compelling exploration of heroism in a world filled with superhuman abilities."
    }

];




export const navLinks = [
    { text: 'Chapter 1', href: `${DOMAIN}/chapter-1` },
    { text: 'Chapter 10', href: `${DOMAIN}/chapter-10` },
    { text: 'Chapter 40', href: `${DOMAIN}/chapter-40` },
];

export const FooterLinks = [
    { text: 'About', href: `${DOMAIN}/about` },
    { text: 'Contact', href: `${DOMAIN}/contact` },
    { text: 'Disclaimer', href: `${DOMAIN}/disclaimer` },
    { text: 'Privacy Policy', href: `${DOMAIN}/privacy-policy` },
    { text: 'Terms & Conditions', href: `${DOMAIN}/terms-and-conditions` }
];







export const chaptersData =

    [
        { "chapterNumber": "1", "numImages": "53" },
        { "chapterNumber": "2", "numImages": "27" },
        { "chapterNumber": "3", "numImages": "24" },
        { "chapterNumber": "4", "numImages": "21" },
        { "chapterNumber": "5", "numImages": "21" },
        { "chapterNumber": "6", "numImages": "21" },
        { "chapterNumber": "7", "numImages": "20" },
        { "chapterNumber": "8", "numImages": "19" },
        { "chapterNumber": "9", "numImages": "23" },
        { "chapterNumber": "10", "numImages": "21" },
        { "chapterNumber": "11", "numImages": "21" },
        { "chapterNumber": "12", "numImages": "23" },
        { "chapterNumber": "13", "numImages": "21" },
        { "chapterNumber": "14", "numImages": "24" },
        { "chapterNumber": "15", "numImages": "21" },
        { "chapterNumber": "16", "numImages": "21" },
        { "chapterNumber": "17", "numImages": "20" },
        { "chapterNumber": "18", "numImages": "18" },
        { "chapterNumber": "19", "numImages": "16" },
        { "chapterNumber": "20", "numImages": "17" },
        { "chapterNumber": "21", "numImages": "20" },
        { "chapterNumber": "22", "numImages": "22" },
        { "chapterNumber": "23", "numImages": "22" },
        { "chapterNumber": "24", "numImages": "20" },
        { "chapterNumber": "25", "numImages": "22" },
        { "chapterNumber": "26", "numImages": "25" },
        { "chapterNumber": "27", "numImages": "26" },
        { "chapterNumber": "28", "numImages": "25" },
        { "chapterNumber": "29", "numImages": "28" },
        { "chapterNumber": "30", "numImages": "26" },
        { "chapterNumber": "31", "numImages": "25" },
        { "chapterNumber": "32", "numImages": "20" },
        { "chapterNumber": "33", "numImages": "23" },
        { "chapterNumber": "34", "numImages": "21" },
        { "chapterNumber": "35", "numImages": "20" },
        { "chapterNumber": "36", "numImages": "22" },
        { "chapterNumber": "37", "numImages": "22" },
        { "chapterNumber": "38", "numImages": "19" },
        { "chapterNumber": "39", "numImages": "22" },
        { "chapterNumber": "40", "numImages": "19" },
        { "chapterNumber": "41", "numImages": "21" },
        { "chapterNumber": "42", "numImages": "20" },
        { "chapterNumber": "43", "numImages": "18" },
        { "chapterNumber": "44", "numImages": "22" },
        { "chapterNumber": "45", "numImages": "21" },
        { "chapterNumber": "46", "numImages": "18" },
        { "chapterNumber": "47", "numImages": "20" },
        { "chapterNumber": "48", "numImages": "22" },
        { "chapterNumber": "49", "numImages": "19" },
        { "chapterNumber": "50", "numImages": "22" },
        { "chapterNumber": "51", "numImages": "20" },
        { "chapterNumber": "52", "numImages": "23" },
        { "chapterNumber": "53", "numImages": "23" },
        { "chapterNumber": "54", "numImages": "21" },
        { "chapterNumber": "55", "numImages": "23" },
        { "chapterNumber": "56", "numImages": "23" },
        { "chapterNumber": "57", "numImages": "23" },
        { "chapterNumber": "58", "numImages": "24" },
        { "chapterNumber": "59", "numImages": "24" },
        { "chapterNumber": "60", "numImages": "24" },
        { "chapterNumber": "61", "numImages": "23" },
        { "chapterNumber": "62", "numImages": "22" },
        { "chapterNumber": "63", "numImages": "20" },
        { "chapterNumber": "64", "numImages": "20" },
        { "chapterNumber": "65", "numImages": "20" },
        { "chapterNumber": "66", "numImages": "22" },
        { "chapterNumber": "67", "numImages": "23" },
        { "chapterNumber": "68", "numImages": "24" },
        { "chapterNumber": "69", "numImages": "23" },
        { "chapterNumber": "70", "numImages": "19" },
        { "chapterNumber": "71", "numImages": "21" },
        { "chapterNumber": "72", "numImages": "21" },
        { "chapterNumber": "73", "numImages": "22" },
        { "chapterNumber": "74", "numImages": "17" },
        { "chapterNumber": "75", "numImages": "20" },
        { "chapterNumber": "76", "numImages": "22" },
        { "chapterNumber": "77", "numImages": "18" },
        { "chapterNumber": "78", "numImages": "19" },
        { "chapterNumber": "79", "numImages": "20" },
        { "chapterNumber": "80", "numImages": "20" },
        { "chapterNumber": "81", "numImages": "18" },
        { "chapterNumber": "82", "numImages": "19" },
        { "chapterNumber": "83", "numImages": "19" },
        { "chapterNumber": "84", "numImages": "27" },
        { "chapterNumber": "85", "numImages": "19" },
        { "chapterNumber": "86", "numImages": "20" },
        { "chapterNumber": "87", "numImages": "17" },
        { "chapterNumber": "88", "numImages": "20" },
        { "chapterNumber": "89", "numImages": "20" },
        { "chapterNumber": "90", "numImages": "23" },
        { "chapterNumber": "91", "numImages": "20" },
        { "chapterNumber": "92", "numImages": "21" },
        { "chapterNumber": "93", "numImages": "21" },
        { "chapterNumber": "94", "numImages": "18" },
        { "chapterNumber": "95", "numImages": "21" },
        { "chapterNumber": "96", "numImages": "19" },
        { "chapterNumber": "97", "numImages": "24" },
        { "chapterNumber": "98", "numImages": "19" },
        { "chapterNumber": "99", "numImages": "19" },
        { "chapterNumber": "100", "numImages": "19" },
        { "chapterNumber": "101", "numImages": "23" },
        { "chapterNumber": "102", "numImages": "21" },
        { "chapterNumber": "103", "numImages": "20" },
        { "chapterNumber": "104", "numImages": "20" },
        { "chapterNumber": "105", "numImages": "19" },
        { "chapterNumber": "106", "numImages": "20" },
        { "chapterNumber": "107", "numImages": "24" },
        { "chapterNumber": "108", "numImages": "25" },
        { "chapterNumber": "109", "numImages": "19" },
        { "chapterNumber": "110", "numImages": "21" },
        { "chapterNumber": "111", "numImages": "22" },
        { "chapterNumber": "112", "numImages": "17" },
        { "chapterNumber": "113", "numImages": "18" },
        { "chapterNumber": "114", "numImages": "18" },
        { "chapterNumber": "115", "numImages": "17" },
        { "chapterNumber": "116", "numImages": "23" },
        { "chapterNumber": "117", "numImages": "15" },
        { "chapterNumber": "118", "numImages": "18" },
        { "chapterNumber": "119", "numImages": "16" },
        { "chapterNumber": "120", "numImages": "20" },
        { "chapterNumber": "121", "numImages": "17" },
        { "chapterNumber": "122", "numImages": "18" },
        { "chapterNumber": "123", "numImages": "19" },
        { "chapterNumber": "124", "numImages": "19" },
        { "chapterNumber": "125", "numImages": "18" },
        { "chapterNumber": "126", "numImages": "20" },
        { "chapterNumber": "127", "numImages": "19" },
        { "chapterNumber": "128", "numImages": "18" },
        { "chapterNumber": "129", "numImages": "16" },
        { "chapterNumber": "130", "numImages": "20" },
        { "chapterNumber": "131", "numImages": "18" },
        { "chapterNumber": "132", "numImages": "19" },
        { "chapterNumber": "133", "numImages": "22" },
        { "chapterNumber": "134", "numImages": "20" },
        { "chapterNumber": "135", "numImages": "22" },
        { "chapterNumber": "136", "numImages": "19" },
        { "chapterNumber": "137", "numImages": "18" },
        { "chapterNumber": "138", "numImages": "19" },
        { "chapterNumber": "139", "numImages": "19" },
        { "chapterNumber": "140", "numImages": "19" },
        { "chapterNumber": "141", "numImages": "15" },
        { "chapterNumber": "142", "numImages": "22" },
        { "chapterNumber": "143", "numImages": "16" },
        { "chapterNumber": "144", "numImages": "37" },
        { "chapterNumber": "145", "numImages": "17" },
        { "chapterNumber": "146", "numImages": "18" },
        { "chapterNumber": "147", "numImages": "20" },
        { "chapterNumber": "148", "numImages": "15" },
        { "chapterNumber": "149", "numImages": "14" },
        { "chapterNumber": "150", "numImages": "16" },
        { "chapterNumber": "151", "numImages": "18" },
        { "chapterNumber": "152", "numImages": "18" },
        { "chapterNumber": "153", "numImages": "16" },
        { "chapterNumber": "154", "numImages": "17" },
        { "chapterNumber": "155", "numImages": "17" },
        { "chapterNumber": "156", "numImages": "17" },
        { "chapterNumber": "157", "numImages": "15" },
        { "chapterNumber": "158", "numImages": "15" },
        { "chapterNumber": "159", "numImages": "17" },
        { "chapterNumber": "160", "numImages": "18" },
        { "chapterNumber": "161", "numImages": "17" },
        { "chapterNumber": "162", "numImages": "13" },
        { "chapterNumber": "163", "numImages": "16" },
        { "chapterNumber": "164", "numImages": "17" },
        { "chapterNumber": "165", "numImages": "17" },
        { "chapterNumber": "166", "numImages": "17" },
        { "chapterNumber": "167", "numImages": "17" },
        { "chapterNumber": "168", "numImages": "17" },
        { "chapterNumber": "169", "numImages": "18" },
        { "chapterNumber": "170", "numImages": "16" },
        { "chapterNumber": "171", "numImages": "15" },
        { "chapterNumber": "172", "numImages": "15" },
        { "chapterNumber": "173", "numImages": "17" },
        { "chapterNumber": "174", "numImages": "17" },
        { "chapterNumber": "175", "numImages": "15" },
        { "chapterNumber": "176", "numImages": "17" },
        { "chapterNumber": "177", "numImages": "16" },
        { "chapterNumber": "178", "numImages": "17" },
        { "chapterNumber": "179", "numImages": "16" },
        { "chapterNumber": "180", "numImages": "16" },
        { "chapterNumber": "181", "numImages": "14" },
        { "chapterNumber": "182", "numImages": "16" },
        { "chapterNumber": "183", "numImages": "17" },
        { "chapterNumber": "184", "numImages": "17" },
        { "chapterNumber": "185", "numImages": "15" },
        { "chapterNumber": "186", "numImages": "16" },
        { "chapterNumber": "187", "numImages": "17" },
        { "chapterNumber": "188", "numImages": "12" },
        { "chapterNumber": "189", "numImages": "15" },
        { "chapterNumber": "190", "numImages": "14" },
        { "chapterNumber": "191", "numImages": "15" },
        { "chapterNumber": "192", "numImages": "19" },
        { "chapterNumber": "193", "numImages": "15" },
        { "chapterNumber": "194", "numImages": "12" },
        { "chapterNumber": "195", "numImages": "16" },
        { "chapterNumber": "196", "numImages": "14" },
        { "chapterNumber": "197", "numImages": "15" },
        { "chapterNumber": "198", "numImages": "13" },
        { "chapterNumber": "199", "numImages": "13" },
        { "chapterNumber": "200", "numImages": "11" },
        { "chapterNumber": "201", "numImages": "20" },
        { "chapterNumber": "202", "numImages": "14" },
        { "chapterNumber": "203", "numImages": "26" },
        { "chapterNumber": "204", "numImages": "15" },
        { "chapterNumber": "205", "numImages": "16" },
        { "chapterNumber": "206", "numImages": "16" },
        { "chapterNumber": "207", "numImages": "16" },
        { "chapterNumber": "208", "numImages": "13" },
        { "chapterNumber": "209", "numImages": "16" },
        { "chapterNumber": "210", "numImages": "16" },
        { "chapterNumber": "211", "numImages": "13" },
        { "chapterNumber": "212", "numImages": "14" },
        { "chapterNumber": "213", "numImages": "14" },
        { "chapterNumber": "214", "numImages": "17" },
        { "chapterNumber": "215", "numImages": "14" },
        { "chapterNumber": "216", "numImages": "14" },
        { "chapterNumber": "217", "numImages": "14" },
        { "chapterNumber": "218", "numImages": "16" },
        { "chapterNumber": "219", "numImages": "15" },
        { "chapterNumber": "220", "numImages": "16" },
        { "chapterNumber": "221", "numImages": "14" },
        { "chapterNumber": "222", "numImages": "15" },
        { "chapterNumber": "223", "numImages": "15" },
        { "chapterNumber": "224", "numImages": "14" },
        { "chapterNumber": "225", "numImages": "15" },
        { "chapterNumber": "226", "numImages": "15" },
        { "chapterNumber": "227", "numImages": "15" },
        { "chapterNumber": "228", "numImages": "14" },
        { "chapterNumber": "229", "numImages": "17" },
        { "chapterNumber": "230", "numImages": "12" },
        { "chapterNumber": "231", "numImages": "16" },
        { "chapterNumber": "232", "numImages": "15" },
        { "chapterNumber": "233", "numImages": "16" },
        { "chapterNumber": "234", "numImages": "15" },
        { "chapterNumber": "235", "numImages": "19" },
        { "chapterNumber": "236", "numImages": "16" },
        { "chapterNumber": "237", "numImages": "16" },
        { "chapterNumber": "238", "numImages": "13" },
        { "chapterNumber": "239", "numImages": "14" },
        { "chapterNumber": "240", "numImages": "14" },
        { "chapterNumber": "241", "numImages": "18" },
        { "chapterNumber": "242", "numImages": "17" },
        { "chapterNumber": "243", "numImages": "20" },
        { "chapterNumber": "244", "numImages": "18" },
        { "chapterNumber": "245", "numImages": "17" },
        { "chapterNumber": "246", "numImages": "16" },
        { "chapterNumber": "247", "numImages": "14" },
        { "chapterNumber": "248", "numImages": "13" },
        { "chapterNumber": "249", "numImages": "15" },
        { "chapterNumber": "250", "numImages": "13" },
        { "chapterNumber": "251", "numImages": "13" },
        { "chapterNumber": "252", "numImages": "13" },
        { "chapterNumber": "253", "numImages": "14" },
        { "chapterNumber": "254", "numImages": "15" },
        { "chapterNumber": "255", "numImages": "15" },
        { "chapterNumber": "256", "numImages": "15" },
        { "chapterNumber": "257", "numImages": "17" },
        { "chapterNumber": "258", "numImages": "15" },
        { "chapterNumber": "259", "numImages": "15" },
        { "chapterNumber": "260", "numImages": "14" },
        { "chapterNumber": "261", "numImages": "16" },
        { "chapterNumber": "262", "numImages": "17" },
        { "chapterNumber": "263", "numImages": "15" },
        { "chapterNumber": "264", "numImages": "17" },
        { "chapterNumber": "265", "numImages": "15" },
        { "chapterNumber": "266", "numImages": "19" },
        { "chapterNumber": "267", "numImages": "20" },
        { "chapterNumber": "268", "numImages": "14" },
        { "chapterNumber": "269", "numImages": "14" },
        { "chapterNumber": "270", "numImages": "18" },
        { "chapterNumber": "271", "numImages": "17" },
        { "chapterNumber": "272", "numImages": "17" },
        { "chapterNumber": "273", "numImages": "16" },
        { "chapterNumber": "274", "numImages": "17" },
        { "chapterNumber": "275", "numImages": "17" },
        { "chapterNumber": "276", "numImages": "18" },
        { "chapterNumber": "277", "numImages": "16" },
        { "chapterNumber": "278", "numImages": "17" },
        { "chapterNumber": "279", "numImages": "17" },
        { "chapterNumber": "280", "numImages": "17" },
        { "chapterNumber": "281", "numImages": "18" },
        { "chapterNumber": "282", "numImages": "15" },
        { "chapterNumber": "283", "numImages": "16" },
        { "chapterNumber": "284", "numImages": "16" },
        { "chapterNumber": "285", "numImages": "16" },
        { "chapterNumber": "286", "numImages": "15" },
        { "chapterNumber": "287", "numImages": "16" },
        { "chapterNumber": "288", "numImages": "16" },
        { "chapterNumber": "289", "numImages": "17" },
        { "chapterNumber": "290", "numImages": "15" },
        { "chapterNumber": "291", "numImages": "14" },
        { "chapterNumber": "292", "numImages": "14" },
        { "chapterNumber": "293", "numImages": "17" },
        { "chapterNumber": "294", "numImages": "15" },
        { "chapterNumber": "295", "numImages": "16" },
        { "chapterNumber": "296", "numImages": "19" },
        { "chapterNumber": "297", "numImages": "19" },
        { "chapterNumber": "298", "numImages": "19" },
        { "chapterNumber": "299", "numImages": "19" },
        { "chapterNumber": "300", "numImages": "16" },
        { "chapterNumber": "301", "numImages": "17" },
        { "chapterNumber": "302", "numImages": "16" },
        { "chapterNumber": "303", "numImages": "15" },
        { "chapterNumber": "304", "numImages": "16" },
        { "chapterNumber": "305", "numImages": "16" },
        { "chapterNumber": "306", "numImages": "17" },
        { "chapterNumber": "307", "numImages": "16" },
        { "chapterNumber": "308", "numImages": "15" },
        { "chapterNumber": "309", "numImages": "17" },
        { "chapterNumber": "310", "numImages": "18" },
        { "chapterNumber": "311", "numImages": "14" },
        { "chapterNumber": "312", "numImages": "14" },
        { "chapterNumber": "313", "numImages": "20" },
        { "chapterNumber": "314", "numImages": "18" },
        { "chapterNumber": "315", "numImages": "15" },
        { "chapterNumber": "316", "numImages": "17" },
        { "chapterNumber": "317", "numImages": "16" },
        { "chapterNumber": "318", "numImages": "14" },
        { "chapterNumber": "319", "numImages": "19" },
        { "chapterNumber": "320", "numImages": "18" },
        { "chapterNumber": "321", "numImages": "15" },
        { "chapterNumber": "322", "numImages": "17" },
        { "chapterNumber": "323", "numImages": "17" },
        { "chapterNumber": "324", "numImages": "17" },
        { "chapterNumber": "325", "numImages": "17" },
        { "chapterNumber": "326", "numImages": "16" },
        { "chapterNumber": "327", "numImages": "16" },
        { "chapterNumber": "328", "numImages": "17" },
        { "chapterNumber": "329", "numImages": "16" },
        { "chapterNumber": "330", "numImages": "17" },
        { "chapterNumber": "331", "numImages": "16" },
        { "chapterNumber": "332", "numImages": "18" },
        { "chapterNumber": "333", "numImages": "16" },
        { "chapterNumber": "334", "numImages": "17" },
        { "chapterNumber": "335", "numImages": "17" },
        { "chapterNumber": "336", "numImages": "17" },
        { "chapterNumber": "337", "numImages": "18" },
        { "chapterNumber": "338", "numImages": "14" },
        { "chapterNumber": "339", "numImages": "16" },
        { "chapterNumber": "340", "numImages": "15" },
        { "chapterNumber": "341", "numImages": "15" },
        { "chapterNumber": "342", "numImages": "17" },
        { "chapterNumber": "343", "numImages": "15" },
        { "chapterNumber": "344", "numImages": "17" },
        { "chapterNumber": "345", "numImages": "11" },
        { "chapterNumber": "346", "numImages": "15" },
        { "chapterNumber": "347", "numImages": "14" },
        { "chapterNumber": "348", "numImages": "13" },
        { "chapterNumber": "349", "numImages": "13" },
        { "chapterNumber": "350", "numImages": "19" },
        { "chapterNumber": "351", "numImages": "17" },
        { "chapterNumber": "352", "numImages": "13" },
        { "chapterNumber": "353", "numImages": "18" },
        { "chapterNumber": "354", "numImages": "16" },
        { "chapterNumber": "355", "numImages": "16" },
        { "chapterNumber": "356", "numImages": "15" },
        { "chapterNumber": "357", "numImages": "15" },
        { "chapterNumber": "358", "numImages": "14" },
        { "chapterNumber": "359", "numImages": "19" },
        { "chapterNumber": "360", "numImages": "17" },
        { "chapterNumber": "361", "numImages": "10" },
        { "chapterNumber": "362", "numImages": "15" },
        { "chapterNumber": "363", "numImages": "14" },
        { "chapterNumber": "364", "numImages": "14" },
        { "chapterNumber": "365", "numImages": "13" },
        { "chapterNumber": "366", "numImages": "16" },
        { "chapterNumber": "367", "numImages": "19" },
        { "chapterNumber": "368", "numImages": "15" },
        { "chapterNumber": "369", "numImages": "15" },
        { "chapterNumber": "370", "numImages": "14" },
        { "chapterNumber": "371", "numImages": "15" },
        { "chapterNumber": "372", "numImages": "15" },
        { "chapterNumber": "373", "numImages": "17" },
        { "chapterNumber": "374", "numImages": "15" },
        { "chapterNumber": "375", "numImages": "14" },
        { "chapterNumber": "376", "numImages": "9" },
        { "chapterNumber": "377", "numImages": "10" },
        { "chapterNumber": "378", "numImages": "14" },
        { "chapterNumber": "379", "numImages": "14" },
        { "chapterNumber": "380", "numImages": "17" },
        { "chapterNumber": "381", "numImages": "14" },
        { "chapterNumber": "382", "numImages": "15" },
        { "chapterNumber": "383", "numImages": "16" },
        { "chapterNumber": "384", "numImages": "15" },
        { "chapterNumber": "385", "numImages": "17" },
        { "chapterNumber": "386", "numImages": "15" },
        { "chapterNumber": "387", "numImages": "16" },
        { "chapterNumber": "388", "numImages": "11" },
        { "chapterNumber": "389", "numImages": "10" },
        { "chapterNumber": "390", "numImages": "11" },
        { "chapterNumber": "391", "numImages": "8" },
        { "chapterNumber": "392", "numImages": "13" },
        { "chapterNumber": "393", "numImages": "15" },
        { "chapterNumber": "394", "numImages": "15" },
        { "chapterNumber": "395", "numImages": "14" },
        { "chapterNumber": "396", "numImages": "15" },
        { "chapterNumber": "397", "numImages": "7" },
        { "chapterNumber": "398", "numImages": "15" },
        { "chapterNumber": "399", "numImages": "14" },
        { "chapterNumber": "400", "numImages": "14" },
        { "chapterNumber": "401", "numImages": "15" },
        { "chapterNumber": "402", "numImages": "14" },
        { "chapterNumber": "403", "numImages": "15" },
        { "chapterNumber": "404", "numImages": "11" },
        { "chapterNumber": "405", "numImages": "14" },
        { "chapterNumber": "406", "numImages": "15" },
        { "chapterNumber": "407", "numImages": "13" },
        { "chapterNumber": "408", "numImages": "12" },
        { "chapterNumber": "409", "numImages": "10" },
        { "chapterNumber": "410", "numImages": "16" },
        { "chapterNumber": "411", "numImages": "13" },
        { "chapterNumber": "412", "numImages": "15" },
        { "chapterNumber": "413", "numImages": "14" },
        { "chapterNumber": "414", "numImages": "14" },
        { "chapterNumber": "415", "numImages": "10" },
        { "chapterNumber": "416", "numImages": "14" },
        { "chapterNumber": "417", "numImages": "15" },
        { "chapterNumber": "418", "numImages": "14" },
        { "chapterNumber": "419", "numImages": "18" },
        { "chapterNumber": "420", "numImages": "16" },
        { "chapterNumber": "421", "numImages": "15" },
        { "chapterNumber": "422", "numImages": "15" },
        { "chapterNumber": "423", "numImages": "16" },
        { "chapterNumber": "424", "numImages": "16" },
        { "chapterNumber": "425", "numImages": "16" },
    ]





export const last5chapters = [
    { "chapterNumber": "421", "numImages": "15" },
    { "chapterNumber": "422", "numImages": "15" },
    { "chapterNumber": "423", "numImages": "16" },
    { "chapterNumber": "424", "numImages": "16" },
    { "chapterNumber": "425", "numImages": "16" },
]